### ISSUE TITLE
Error on any click of a page: Cannot read properties of undefined

### ISSUE THREAD

**Issue by krixano** [vuetifyjs/create-vuetify#26]
I used `yarn create vuetify` and set the settings to use Essentials (Vuetify, VueRouter, and Pinia), and to use typescript. When I launch `yarn dev` and go to the website, any click on any page produces the error below:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Array.<anonymous> (content.js:7:89199)
    at c.trigger (content.js:7:81786)
    at HTMLDocument.<anonymous> (content.js:7:81253)
```

It also happens for the keydown, input, change, and focus events. In the compiled code, all of these places use `e.path[0]`. I do not know if this is a vuetify problem, or if it is a problem with the default template given by yarn create vuetify. However, both the JS and Typescript versions have this same bug.

**Comment by krixano** [comment]
Aha! I apologize. For some reason I was assuming it was coming from the vue application itself, but it was in fact from an extension. Thanks for helping.
